#!/usr/bin/env bash
# Reconcile GitHub issues from a docs gap scan.
#
# - Upserts ONE pinned "Documentation Health" dashboard issue (score + full checklist),
#   updated in place each run.
# - Promotes only HIGH-priority actions to individual, assignable issues, deduplicated by a
#   hidden `<!-- docs-gap-id: <id> -->` marker so re-runs update instead of creating duplicates.
# - Closes any previously-opened gap issue whose id is no longer reported (self-healing).
#
# Requires: gh, jq. Env: GH_TOKEN (or gh auth), GH_REPO (defaults to $GITHUB_REPOSITORY).
set -euo pipefail

METRICS="${1:-docs-gap-metrics.json}"
REPO="${GH_REPO:-${GITHUB_REPOSITORY:?set GH_REPO or GITHUB_REPOSITORY}}"
GAP_LABEL="docs-gap"
DASH_LABEL="docs-health-dashboard"

[ -f "$METRICS" ] || { echo "metrics file not found: $METRICS" >&2; exit 1; }

score=$(jq -r '.health_score' "$METRICS")
grade=$(jq -r '.grade' "$METRICS")
gen=$(jq -r '.generated' "$METRICS")

gh() { command gh "$@" --repo "$REPO"; }

# Nest a child issue under the dashboard as a native GitHub sub-issue (idempotent:
# re-adding an existing link is a no-op). The sub_issues API needs the child's REST
# integer id, not its issue number.
link_sub() { # $1 = parent issue number, $2 = child issue number
  local cid
  cid=$(command gh api "repos/$REPO/issues/$2" --jq .id 2>/dev/null) || return 0
  command gh api -X POST "repos/$REPO/issues/$1/sub_issues" -F sub_issue_id="$cid" >/dev/null 2>&1 || true
}

# Labels (idempotent).
gh label create "$GAP_LABEL"  --color FBCA04 --description "Auto-tracked documentation gap" >/dev/null 2>&1 || true
gh label create "$DASH_LABEL" --color 0E8A16 --description "Documentation health dashboard"  >/dev/null 2>&1 || true

# ---------------------------------------------------------------------------
# 1. Dashboard issue (one, pinned, updated in place)
# ---------------------------------------------------------------------------
body=$(mktemp)
{
  echo "<!-- docs-gap-id: _dashboard -->"
  echo "_Auto-generated by the docs gap scan. Generated: ${gen}. Do not edit by hand._"
  echo
  echo "## Score: ${score}/100 (Grade ${grade})"
  echo
  echo "| Component | Score |"
  echo "|---|---|"
  jq -r '.score_breakdown | "| Coverage | \(.coverage)/50 |\n| Pillars | \(.pillars)/20 |\n| Accuracy | \(.accuracy)/20 |\n| Config | \(.config)/10 |"' "$METRICS"
  echo
  echo "## Action plan"
  for pr in high medium low; do
    lines=$(jq -r --arg p "$pr" '.action_items[]? | select(.priority==$p) | "- [ ] **+\(.points)** \(.title) (_\(.where)_)"' "$METRICS")
    if [ -n "$lines" ]; then
      printf '\n### %s priority\n%s\n' "$(echo "$pr" | tr '[:lower:]' '[:upper:]')" "$lines"
    fi
  done
  echo
  echo "High-priority items are also tracked as sub-issues of this dashboard (individual \`${GAP_LABEL}\` issues) and close automatically when resolved."
} > "$body"

dash_title="Documentation Health: ${score}/100 (Grade ${grade})"
dash_num=$(gh issue list --label "$DASH_LABEL" --state open --json number -q '.[0].number // empty')
if [ -n "$dash_num" ]; then
  gh issue edit "$dash_num" --title "$dash_title" --body-file "$body" >/dev/null
  echo "dashboard: updated #$dash_num"
else
  url=$(gh issue create --title "$dash_title" --label "$DASH_LABEL" --body-file "$body")
  dash_num="${url##*/}"
  gh issue pin "$dash_num" >/dev/null 2>&1 || true
  echo "dashboard: created #$dash_num"
fi

# ---------------------------------------------------------------------------
# 2. High-priority individual issues (create / update / close by id marker)
# ---------------------------------------------------------------------------
# Indexed arrays + while-read only: portable to bash 3.2 (macOS), which has
# neither mapfile nor associative arrays.
high_ids=()
while IFS= read -r id; do
  [ -n "$id" ] && high_ids+=("$id")
done < <(jq -r '.action_items[]? | select(.priority=="high") | .id' "$METRICS")

is_high() {
  local i n=${#high_ids[@]}
  for ((i=0; i<n; i++)); do [ "${high_ids[$i]}" = "$1" ] && return 0; done
  return 1
}

# Existing open gap issues as parallel arrays (id parsed from the hidden marker).
existing_nums=(); existing_ids=()
while IFS=$'\t' read -r num id; do
  [ -n "${id:-}" ] && { existing_nums+=("$num"); existing_ids+=("$id"); }
done < <(gh issue list --label "$GAP_LABEL" --state open --limit 200 --json number,body \
           -q '.[] | [(.number|tostring), ((.body | capture("docs-gap-id: (?<i>[a-z0-9-]+)")).i // "")] | @tsv')

num_for_id() {
  local i n=${#existing_ids[@]}
  for ((i=0; i<n; i++)); do
    [ "${existing_ids[$i]}" = "$1" ] && { echo "${existing_nums[$i]}"; return 0; }
  done
  return 1
}

# Create or update each high item.
hcount=${#high_ids[@]}
for ((hi=0; hi<hcount; hi++)); do
  id="${high_ids[$hi]}"
  item=$(jq -c --arg id "$id" '.action_items[] | select(.id==$id)' "$METRICS")
  title="Docs gap: $(jq -r '.title' <<<"$item") (+$(jq -r '.points' <<<"$item"))"
  ibody=$(mktemp)
  {
    echo "<!-- docs-gap-id: ${id} -->"
    echo "**Why it matters:** $(jq -r '.why' <<<"$item")"
    echo
    echo "**Where:** $(jq -r '.where' <<<"$item")"
    echo
    echo "**Effort:** $(jq -r '.effort' <<<"$item") · **Score impact:** +$(jq -r '.points' <<<"$item")"
    echo
    echo "_Auto-tracked by the docs gap scan; closes automatically when the gap is no longer detected._"
  } > "$ibody"
  n=$(num_for_id "$id" || true)
  if [ -n "$n" ]; then
    cur_title=$(gh issue view "$n" --json title -q .title)
    if [ "$cur_title" != "$title" ]; then
      gh issue edit "$n" --title "$title" --body-file "$ibody" >/dev/null
      echo "gap $id: updated #$n"
    else
      echo "gap $id: unchanged #$n"
    fi
  else
    url=$(gh issue create --title "$title" --label "$GAP_LABEL" --body-file "$ibody")
    n="${url##*/}"
    echo "gap $id: created #$n"
  fi
  link_sub "$dash_num" "$n"
done

# Close gap issues whose id is no longer high-priority in this run.
ecount=${#existing_ids[@]}
for ((i=0; i<ecount; i++)); do
  id="${existing_ids[$i]}"
  if ! is_high "$id"; then
    gh issue close "${existing_nums[$i]}" \
      --comment "Resolved: no longer flagged by the docs gap scan (run ${gen})." >/dev/null
    echo "gap $id: closed #${existing_nums[$i]}"
  fi
done
